import { Navigation } from "./components/Navigation";
import { Inter } from 'next/font/google';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const inter = Inter({ subsets: ['latin'] });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Ipuc Llanaditas</title>
      </head>
      <body className={inter.className}>
<Navigation/>
        {children}
      </body>
    </html>
  );
}
